name: 📖 Presentation Request
description: Request to Present about this repository
title: "📖 Presentation Request: <where at...?> "
labels: ["PresentationRequest"]
projects: ["kilasuit/13"]
assignees:
  - kilasuit
body:
- type: textarea
  id: PresentationRequest
  attributes:
    label: Summary
    description: Please a link (ideally via a form) 
    placeholder: |
      Are you requesting me to present about this?
      Do you want to present about this?
  validations:
    required: true
- type: textarea
  id: ContactLink
  attributes:
    label: Contact link
    description: How to get in contact with you
    placeholder: |
      
      I have this Contact Form : https://blog.kilasuit.com/contact-me 
      If you use this, then submit this issue (to get the Issue number), 
      then the form (as it requires a link to the issue)

      If you filled that out, just put "I've filled out the contact form" here.

      However, I would prefer if you could send me a PGP encrypted message pasted here.
      My Current PGP key is on my github profile readme. 

      Don't know about PGP & want me to walk through PGP with you?
      Use the contact form and we can set up a time to chat about it.
  validations:
    required: true
- type: textarea
  id: AdditionalInfo
  attributes:
    label: Anything else?
    description: |
      Any other comments, like did you like this Project?
      Have you used this Project & linked projects to help you with your work?
      If no other comments, please put N/A or None
  validations:
    required: true